In [1]:
import pandas as pd

In [26]:
# read html file
url = "https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_population"
df = pd.read_html(url)

In [23]:
# show table
df

[    States and union territories of India ordered by
 0  Area Population GDP (per capita) Abbreviations...
 1  .mw-parser-output .navbar{display:inline;font-...,
      Rank                  State or union territory     Population  \
 0       1                             Uttar Pradesh      199812341
 1       2                               Maharashtra      112374333
 2       3                                     Bihar      104099452
 3       4                               West Bengal       91276115
 4       5                            Madhya Pradesh       72626809
 5       6                                Tamil Nadu       72147030
 6       7                                 Rajasthan       68548437
 7       8                                 Karnataka       61095297
 8       9                                   Gujarat       60439692
 9      10                            Andhra Pradesh  49,577,103[b]
 10     11                                    Odisha       41974219
 11     12                                 Telangana       35003674
 12     13                                    Kerala       33406061
 13     14                                 Jharkhand       32988134
 14     15                                     Assam       31205576
 15     16                                    Punjab       27743338
 16     17                              Chhattisgarh       25545198
 17     18                                   Haryana       25351462
 18    UT1                              NCT of Delhi       16787941
 19    UT2                         Jammu and Kashmir       12267032
 20     19                               Uttarakhand       10086292
 21     20                          Himachal Pradesh        6864602
 22     21                                   Tripura        3673917
 23     22                                 Meghalaya        2966889
 24     23                                Manipur[d]        2570390
 25     24                                  Nagaland        1978502
 26     25                                       Goa        1458545
 27     26                         Arunachal Pradesh        1383727
 28    UT3                                Puducherry        1247953
 29     27                                   Mizoram        1097206
 30    UT4                                Chandigarh        1055450
 31     28                                    Sikkim         610577
 32    UT5  Dadra and Nagar Haveli and Daman and Diu         585764
 33    UT6               Andaman and Nicobar Islands         380581
 34    UT7                                    Ladakh         274000
 35    UT8                               Lakshadweep          64473
 36  Total                                     India     1210569573

    National Share (%) Decadal growth(2001–2012)  Rural population  \
 0                 NaN                     20.2%         155317278
 1                 NaN                     20.0%          61556074
 2                 NaN                     25.4%          92341436
 3                 NaN                     13.8%          62183113
 4                 NaN                     16.3%          52557404
 5                 NaN                     15.6%          37229590
 6                 NaN                     21.3%          51500352
 7                 NaN                     15.6%          30069335
 8                 NaN                     19.3%          34694609
 9                 NaN                     11.0%          34966693
 10                NaN                     14.0%          34970562
 11                NaN                    13.58%          21395009
 12                NaN                      4.9%          17471135
 13                NaN                     22.4%          25055073
 14              2.58%                     17.7%          26807034
 15              2.29%                    13.89%          17344192
 16                NaN                     22.6%          19607961
 17                NaN                     19.9%          16509359
 18                NaN                     21.2%            419042
 19                NaN                     23.6%           9064220
 20                NaN                     18.8%           7036954
 21                NaN                     12.9%           6176050
 22                NaN                     14.8%           2712464
 23                NaN                     27.9%           2371439
 24                NaN                     18.6%           1793875
 25                NaN                     −0.6%           1407536
 26                NaN                      8.2%            551731
 27                NaN                     26.0%           1066358
 28                NaN                     28.1%            395200
 29                NaN                     23.5%            525435
 30                NaN                     17.2%             28991
 31                NaN                     12.9%            456999
 32                NaN                     55.1%            243510
 33                NaN                      6.9%            237093
 34                NaN                     17.8%             43840
 35                NaN                      6.3%             14141
 36               100%                     17.7%         833463448

    Percent rural  Urban population Percent urban  \
 0            NaN          44495063           NaN
 1            NaN          50818259           NaN
 2            NaN          11758016           NaN
 3            NaN          29093002           NaN
 4            NaN          20069405           NaN
 5            NaN          34917440           NaN
 6            NaN          17048085           NaN
 7            NaN          31025962           NaN
 8            NaN          25745083           NaN
 9            NaN          14610410           NaN
 10           NaN           7003656           NaN
 11           NaN          13608665           NaN
 12           NaN          15934926           NaN
 13           NaN           7933061           NaN
 14        85.90%           4398542        14.10%
 15        62.52%          10399146        37.48%
 16           NaN           5937237           NaN
 17           NaN           8842103           NaN
 18           NaN          16368899           NaN
 19           NaN           3202812           NaN
 20           NaN           3049338           NaN
 21           NaN            688552           NaN
 22           NaN            961453           NaN
 23           NaN            595450           NaN
 24           NaN            776515           NaN
 25           NaN            570966           NaN
 26           NaN            906814           NaN
 27           NaN            317369           NaN
 28           NaN            852753           NaN
 29           NaN            571771           NaN
 30           NaN           1026459           NaN
 31           NaN            153578           NaN
 32           NaN            342254           NaN
 33           NaN            143488           NaN
 34           NaN            230160           NaN
 35           NaN             50332           NaN
 36        68.84%         377106125        31.16%

                               Area[16]                 Density[a]  Sex ratio
 0           240,928 km2 (93,023 sq mi)      828/km2 (2,140/sq mi)        912
 1          307,713 km2 (118,809 sq mi)        365/km2 (950/sq mi)        929
 2            94,163 km2 (36,357 sq mi)    1,102/km2 (2,850/sq mi)        918
 3            88,752 km2 (34,267 sq mi)    1,029/km2 (2,670/sq mi)        953
 4          308,245 km2 (119,014 sq mi)        236/km2 (610/sq mi)        931
 5           130,051 km2 (50,213 sq mi)      555/km2 (1,440/sq mi)        996
 6          342,239 km2 (132,139 sq mi)        201/km2 (520/sq mi)        928
 7           191,791 km2 (74,051 sq mi)        319/km2 (830/sq mi)        979
 8           196,024 km2 (75,685 sq mi)        308/km2 (800/sq mi)        919
 9           162,968 km2 (62,922 sq mi)        303/km2 (780/sq mi)        993
 10          155,707 km2 (60,119 sq mi)        269/km2 (700/sq mi)        979
 11          112,077 km2 (43,273 sq mi)        312/km2 (810/sq mi)        988
 12           38,863 km2 (15,005 sq mi)      859/km2 (2,220/sq mi)       1084
 13           79,714 km2 (30,778 sq mi)      414/km2 (1,070/sq mi)        948
 14           78,438 km2 (30,285 sq mi)      398/km2 (1,030/sq mi)        958
 15           50,362 km2 (19,445 sq mi)      551/km2 (1,430/sq mi)        895
 16          135,191 km2 (52,198 sq mi)        189/km2 (490/sq mi)        991
 17           44,212 km2 (17,070 sq mi)      573/km2 (1,480/sq mi)        879
 18               1,484 km2 (573 sq mi)  11,297/km2 (29,260/sq mi)        868
 19        42,241 km2 (16,309 sq mi)[c]        297/km2 (770/sq mi)        890
 20           53,483 km2 (20,650 sq mi)        189/km2 (490/sq mi)        963
 21           55,673 km2 (21,495 sq mi)        123/km2 (320/sq mi)        972
 22            10,486 km2 (4,049 sq mi)        350/km2 (910/sq mi)        960
 23            22,429 km2 (8,660 sq mi)        132/km2 (340/sq mi)        989
 24            22,327 km2 (8,621 sq mi)        122/km2 (320/sq mi)        992
 25            16,579 km2 (6,401 sq mi)        119/km2 (310/sq mi)        931
 26             3,702 km2 (1,429 sq mi)      394/km2 (1,020/sq mi)        973
 27           83,743 km2 (32,333 sq mi)          17/km2 (44/sq mi)        938
 28                 479 km2 (185 sq mi)    2,598/km2 (6,730/sq mi)       1037
 29            21,081 km2 (8,139 sq mi)         52/km2 (130/sq mi)        976
 30                  114 km2 (44 sq mi)   9,252/km2 (23,960/sq mi)        818
 31             7,096 km2 (2,740 sq mi)         86/km2 (220/sq mi)        890
 32                 603 km2 (233 sq mi)      970/km2 (2,500/sq mi)        711
 33             8,249 km2 (3,185 sq mi)         46/km2 (120/sq mi)        876
 34        96,701 km2 (37,336 sq mi)[e]        2.8/km2 (7.3/sq mi)        853
 35                   32 km2 (12 sq mi)    2,013/km2 (5,210/sq mi)        946
 36  3,287,240 km2 (1,269,210 sq mi)[f]        382/km2 (990/sq mi)        940  ]

In [28]:
# length
len(df)

2

In [34]:
df[0]

    States and union territories of India ordered by
0  Area Population GDP (per capita) Abbreviations...
1  .mw-parser-output .navbar{display:inline;font-...

In [33]:
df[1]

,Rank,State or union territory,Population,National Share (%),Decadal growth(2001–2012),Rural population,Percent rural,Urban population,Percent urban,Area[16],Density[a],Sex ratio
0,1,Uttar Pradesh,199812341,NaN,20.2%,155317278,NaN,44495063,NaN,"240,928 km2 (93,023 sq mi)","828/km2 (2,140/sq mi)",912
1,2,Maharashtra,112374333,NaN,20.0%,61556074,NaN,50818259,NaN,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929
2,3,Bihar,104099452,NaN,25.4%,92341436,NaN,11758016,NaN,"94,163 km2 (36,357 sq mi)","1,102/km2 (2,850/sq mi)",918
3,4,West Bengal,91276115,NaN,13.8%,62183113,NaN,29093002,NaN,"88,752 km2 (34,267 sq mi)","1,029/km2 (2,670/sq mi)",953
4,5,Madhya Pradesh,72626809,NaN,16.3%,52557404,NaN,20069405,NaN,"308,245 km2 (119,014 sq mi)",236/km2 (610/sq mi),931
5,6,Tamil Nadu,72147030,NaN,15.6%,37229590,NaN,34917440,NaN,"130,051 km2 (50,213 sq mi)","555/km2 (1,440/sq mi)",996
6,7,Rajasthan,68548437,NaN,21.3%,51500352,NaN,17048085,NaN,"342,239 km2 (132,139 sq mi)",201/km2 (520/sq mi),928
7,8,Karnataka,61095297,NaN,15.6%,30069335,NaN,31025962,NaN,"191,791 km2 (74,051 sq mi)",319/km2 (830/sq mi),979
8,9,Gujarat,60439692,NaN,19.3%,34694609,NaN,25745083,NaN,"196,024 km2 (75,685 sq mi)",308/km2 (800/sq mi),919
9,10,Andhra Pradesh,"49,577,103[b]",NaN,11.0%,34966693,NaN,14610410,NaN,"162,968 km2 (62,922 sq mi)",303/km2 (780/sq mi),993
10,11,Odisha,41974219,NaN,14.0%,34970562,NaN,7003656,NaN,"155,707 km2 (60,119 sq mi)",269/km2 (700/sq mi),979
11,12,Telangana,35003674,NaN,13.58%,21395009,NaN,13608665,NaN,"112,077 km2 (43,273 sq mi)",312/km2 (810/sq mi),988
12,13,Kerala,33406061,NaN,4.9%,17471135,NaN,15934926,NaN,"38,863 km2 (15,005 sq mi)","859/km2 (2,220/sq mi)",1084
13,14,Jharkhand,32988134,NaN,22.4%,25055073,NaN,7933061,NaN,"79,714 km2 (30,778 sq mi)","414/km2 (1,070/sq mi)",948
14,15,Assam,31205576,2.58%,17.7%,26807034,85.90%,4398542,14.10%,"78,438 km2 (30,285 sq mi)","398/km2 (1,030/sq mi)",958
15,16,Punjab,27743338,2.29%,13.89%,17344192,62.52%,10399146,37.48%,"50,362 km2 (19,445 sq mi)","551/km2 (1,430/sq mi)",895
16,17,Chhattisgarh,25545198,NaN,22.6%,19607961,NaN,5937237,NaN,"135,191 km2 (52,198 sq mi)",189/km2 (490/sq mi),991
17,18,Haryana,25351462,NaN,19.9%,16509359,NaN,8842103,NaN,"44,212 km2 (17,070 sq mi)","573/km2 (1,480/sq mi)",879
18,UT1,NCT of Delhi,16787941,NaN,21.2%,419042,NaN,16368899,NaN,"1,484 km2 (573 sq mi)","11,297/km2 (29,260/sq mi)",868
19,UT2,Jammu and Kashmir,12267032,NaN,23.6%,9064220,NaN,3202812,NaN,"42,241 km2 (16,309 sq mi)[c]",297/km2 (770/sq mi),890
20,19,Uttarakhand,10086292,NaN,18.8%,7036954,NaN,3049338,NaN,"53,483 km2 (20,650 sq mi)",189/km2 (490/sq mi),963
21,20,Himachal Pradesh,6864602,NaN,12.9%,6176050,NaN,688552,NaN,"55,673 km2 (21,495 sq mi)",123/km2 (320/sq mi),972
22,21,Tripura,3673917,NaN,14.8%,2712464,NaN,961453,NaN,"10,486 km2 (4,049 sq mi)",350/km2 (910/sq mi),960
23,22,Meghalaya,2966889,NaN,27.9%,2371439,NaN,595450,NaN,"22,429 km2 (8,660 sq mi)",132/km2 (340/sq mi),989
24,23,Manipur[d],2570390,NaN,18.6%,1793875,NaN,776515,NaN,"22,327 km2 (8,621 sq mi)",122/km2 (320/sq mi),992
25,24,Nagaland,1978502,NaN,−0.6%,1407536,NaN,570966,NaN,"16,579 km2 (6,401 sq mi)",119/km2 (310/sq mi),931
26,25,Goa,1458545,NaN,8.2%,551731,NaN,906814,NaN,"3,702 km2 (1,429 sq mi)","394/km2 (1,020/sq mi)",973
27,26,Arunachal Pradesh,1383727,NaN,26.0%,1066358,NaN,317369,NaN,"83,743 km2 (32,333 sq mi)",17/km2 (44/sq mi),938
28,UT3,Puducherry,1247953,NaN,28.1%,395200,NaN,852753,NaN,479 km2 (185 sq mi),"2,598/km2 (6,730/sq mi)",1037
29,27,Mizoram,1097206,NaN,23.5%,525435,NaN,571771,NaN,"21,081 km2 (8,139 sq mi)",52/km2 (130/sq mi),976
30,UT4,Chandigarh,1055450,NaN,17.2%,28991,NaN,1026459,NaN,114 km2 (44 sq mi),"9,252/km2 (23,960/sq mi)",818
31,28,Sikkim,610577,NaN,12.9%,456999,NaN,153578,NaN,"7,096 km2 (2,740 sq mi)",86/km2 (220/sq mi),890
32,UT5,Dadra and Nagar Haveli and Daman and Diu,585764,NaN,55.1%,243510,NaN,342254,NaN,603 km2 (233 sq mi),"970/km2 (2,500/sq mi)",711
33,UT6,Andaman and Nicobar Islands,380581,NaN,6.9%,237093,NaN,143488,NaN,"8,249 km2 (3,185 sq mi)",46/km2 (120/sq mi),876
34,UT7,Ladakh,274000,NaN,17.8%,43840,NaN,230160,NaN,"96,701 km2 (37,336 sq mi)[e]",2.8/km2 (7.3/sq mi),853
35,UT8,Lakshadweep,64473,NaN,6.3%,14141,NaN,50332,NaN,32 km2 (12 sq mi),"2,013/km2 (5,210/sq mi)",946
36,Total,India,1210569573,100%,17.7%,833463448,68.84%,377106125,31.16%,"3,287,240 km2 (1,269,210 sq mi)[f]",382/km2 (990/sq mi),940